# FortunaMind Persistent MCP Server - Render.com Blueprint Configuration
# Infrastructure as Code for automated deployment
version: 1

services:
  # =============================================================================
  # Main HTTP MCP Server (Primary Service)
  # =============================================================================
  - name: fortunamind-persistent-mcp
    type: web
    runtime: python3
    region: oregon  # US West (Oregon) - adjust based on your location
    branch: main
    buildCommand: |
      echo "🔧 Installing dependencies..."
      pip install --upgrade pip
      pip install -r requirements.txt
      
      echo "🗄️ Running database migrations..."
      if [ ! -z "$DATABASE_URL" ]; then
        export PYTHONPATH="/app/src:$PYTHONPATH"
        alembic upgrade head
        echo "✅ Database migrations completed"
      else
        echo "⚠️ DATABASE_URL not set, skipping migrations"
      fi
      
      echo "🧪 Testing persistence library..."
      PYTHONPATH="/app/src:$PYTHONPATH" python -c "
import sys
sys.path.insert(0, 'src')
try:
    from fortunamind_persistence.storage import SupabaseStorage
    from fortunamind_persistence.subscription import SubscriptionValidator
    from fortunamind_persistence.rate_limiting import RateLimiter
    print('✅ Persistence library modules imported successfully')
except Exception as e:
    print(f'❌ Import error: {e}')
    sys.exit(1)
"
      echo "🚀 Build completed - ready to start server"
    startCommand: |
      export PYTHONPATH="/app/src:$PYTHONPATH"
      echo "🚀 Starting FortunaMind Persistent MCP Server..."
      echo "PYTHONPATH: $PYTHONPATH"
      echo "PORT: ${PORT:-8000}"
      python server.py
    plan: starter  # Start with $7/month, upgrade to 'standard' for production

    # Environment Configuration
    env:
      # Server Configuration
      - key: SERVER_MODE
        value: http
      - key: SERVER_HOST
        value: 0.0.0.0
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: LOG_FORMAT
        value: json
      - key: MCP_SERVER_NAME
        value: "FortunaMind-Persistent-MCP-Production"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      
      # Security Configuration  
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: SECURITY_PROFILE
        value: STRICT
        
      # Feature Flags
      - key: ENABLE_TRADING_JOURNAL
        value: true
      - key: ENABLE_TECHNICAL_INDICATORS
        value: true
      - key: ENABLE_PORTFOLIO_INTEGRATION
        value: true
      - key: ENABLE_PRE_TRADE_ANALYSIS
        value: true
      - key: ENABLE_ADVANCED_ANALYTICS
        value: false
      - key: ENABLE_PREDICTIVE_INSIGHTS
        value: false
        
      # Rate Limiting
      - key: API_RATE_LIMIT_PER_MINUTE
        value: 100
      - key: MAX_JOURNAL_ENTRY_LENGTH
        value: 2000
        
      # Production Persistence Configuration
      # ⚠️ CRITICAL: These MUST be set as encrypted environment variables in Render Dashboard
      # DO NOT set real values here - they will be visible in version control
      - key: DATABASE_URL
        sync: false  # Set manually in Render dashboard with real Supabase connection string
      - key: SUPABASE_URL  
        sync: false  # Set manually in Render dashboard with real project URL
      - key: SUPABASE_ANON_KEY
        sync: false  # Set manually in Render dashboard with real anon key
        
      # Optional: Advanced features (can be enabled in dashboard)
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false  # Only needed for admin operations, set in dashboard if required
        
      # Render-specific Configuration
      - key: RENDER
        value: true
      - key: PYTHONPATH
        value: /opt/render/project/src

    # Health Check Configuration
    healthCheckPath: /health

    # Auto-scaling Configuration
    scaling:
      minInstances: 1
      maxInstances: 3

# =============================================================================
# Blueprint Metadata
# =============================================================================
metadata:
  # Blueprint information
  name: "FortunaMind Persistent MCP Server Platform"
  description: "Educational crypto tools with persistent storage for crypto-curious professionals"
  version: "1.0.0"

  # Contact information
  maintainer: "FortunaMind Team"
  repository: "https://github.com/awinskill/fortunamind-persistent-mcp"

  # Documentation links
  documentation: "https://github.com/awinskill/fortunamind-persistent-mcp/blob/main/README.md"
  deploymentGuide: "./RENDER_DEPLOYMENT_GUIDE.md"