# FortunaMind Persistent MCP Server - Render.com Blueprint Configuration
# Infrastructure as Code for automated deployment
version: 1

services:
  # =============================================================================
  # Main HTTP MCP Server (Primary Service)
  # =============================================================================
  - name: fortunamind-persistent-mcp
    type: web
    runtime: docker
    region: oregon  # US West (Oregon) - adjust based on your location
    branch: main
    buildCommand: ""  # Docker build handled automatically
    plan: starter  # Start with $7/month, upgrade to 'standard' for production

    # Environment Configuration
    env:
      # Server Configuration
      - key: SERVER_MODE
        value: http
      - key: SERVER_HOST
        value: 0.0.0.0
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: LOG_FORMAT
        value: json
      - key: MCP_SERVER_NAME
        value: "FortunaMind-Persistent-MCP-Production"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      
      # Security Configuration  
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: SECURITY_PROFILE
        value: STRICT
        
      # Feature Flags
      - key: ENABLE_TRADING_JOURNAL
        value: true
      - key: ENABLE_TECHNICAL_INDICATORS
        value: true
      - key: ENABLE_PORTFOLIO_INTEGRATION
        value: true
      - key: ENABLE_PRE_TRADE_ANALYSIS
        value: true
      - key: ENABLE_ADVANCED_ANALYTICS
        value: false
      - key: ENABLE_PREDICTIVE_INSIGHTS
        value: false
        
      # Rate Limiting
      - key: API_RATE_LIMIT_PER_MINUTE
        value: 100
      - key: MAX_JOURNAL_ENTRY_LENGTH
        value: 2000
        
      # Mock settings for demo deployment (override in Render dashboard for production)
      - key: MOCK_SUBSCRIPTION_CHECK
        value: true
      - key: MOCK_TECHNICAL_DATA
        value: true
      - key: DATABASE_URL
        value: "postgresql://mock:mock@mock:5432/mock"
      - key: SUPABASE_URL
        value: "https://mock.supabase.co"
      - key: SUPABASE_ANON_KEY
        value: "mock-anon-key-replace-in-dashboard"
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: "mock-service-key-replace-in-dashboard"
        
      # Render-specific Configuration
      - key: RENDER
        value: true

    # Health Check Configuration
    healthCheckPath: /health

    # Auto-scaling Configuration
    scaling:
      minInstances: 1
      maxInstances: 3

# =============================================================================
# Blueprint Metadata
# =============================================================================
metadata:
  # Blueprint information
  name: "FortunaMind Persistent MCP Server Platform"
  description: "Educational crypto tools with persistent storage for crypto-curious professionals"
  version: "1.0.0"

  # Contact information
  maintainer: "FortunaMind Team"
  repository: "https://github.com/awinskill/fortunamind-persistent-mcp"

  # Documentation links
  documentation: "https://github.com/awinskill/fortunamind-persistent-mcp/blob/main/README.md"
  deploymentGuide: "./RENDER_DEPLOYMENT_GUIDE.md"